import 'package:flutter/material.dart';

class AvatarCity {
  final String name;
  final String country;
  final String flag;
  final String? svgPath;

  const AvatarCity({
    required this.name,
    required this.country,
    required this.flag,
    this.svgPath,
  });

  Color get backgroundColor {
    final hash = name.codeUnits.fold(0, (a, b) => (a * 31 + b) & 0x7FFFFFFF);
    final hue = (hash % 360).toDouble();
    final sat = (0.50 + ((hash >> 8) & 0x3F) / 255.0 * 0.30).clamp(0.0, 1.0);
    final lit = (0.24 + ((hash >> 16) & 0x1F) / 255.0 * 0.12).clamp(0.0, 1.0);
    return HSLColor.fromAHSL(1, hue, sat, lit).toColor();
  }
}

// Keep old names for backward-compat with existing code
const avatarPaths = <String>[
  'assets/avatars/paris.svg',
  'assets/avatars/london.svg',
  'assets/avatars/newyork.svg',
  'assets/avatars/tokyo.svg',
  'assets/avatars/rome.svg',
  'assets/avatars/barcelona.svg',
  'assets/avatars/sydney.svg',
  'assets/avatars/dubai.svg',
  'assets/avatars/warsaw.svg',
];

const avatarLabels = <String>[
  'Paris', 'London', 'New York', 'Tokyo', 'Rome',
  'Barcelona', 'Sydney', 'Dubai', 'Warsaw',
];

const List<AvatarCity> allAvatars = [
  // ── Featured cities with hand-drawn landmarks ──────────────────────────────
  AvatarCity(name: 'Paris',      country: 'France',    flag: '🇫🇷', svgPath: 'assets/avatars/paris.svg'),
  AvatarCity(name: 'London',     country: 'UK',        flag: '🇬🇧', svgPath: 'assets/avatars/london.svg'),
  AvatarCity(name: 'New York',   country: 'USA',       flag: '🇺🇸', svgPath: 'assets/avatars/newyork.svg'),
  AvatarCity(name: 'Tokyo',      country: 'Japan',     flag: '🇯🇵', svgPath: 'assets/avatars/tokyo.svg'),
  AvatarCity(name: 'Rome',       country: 'Italy',     flag: '🇮🇹', svgPath: 'assets/avatars/rome.svg'),
  AvatarCity(name: 'Barcelona',  country: 'Spain',     flag: '🇪🇸', svgPath: 'assets/avatars/barcelona.svg'),
  AvatarCity(name: 'Sydney',     country: 'Australia', flag: '🇦🇺', svgPath: 'assets/avatars/sydney.svg'),
  AvatarCity(name: 'Dubai',      country: 'UAE',       flag: '🇦🇪', svgPath: 'assets/avatars/dubai.svg'),
  AvatarCity(name: 'Warsaw',     country: 'Poland',    flag: '🇵🇱', svgPath: 'assets/avatars/warsaw.svg'),

  // ── Africa ─────────────────────────────────────────────────────────────────
  AvatarCity(name: 'Algiers',         country: 'Algeria',                    flag: '🇩🇿', svgPath: 'assets/avatars/algiers.svg'),
  AvatarCity(name: 'Luanda',          country: 'Angola',                     flag: '🇦🇴', svgPath: 'assets/avatars/luanda.svg'),
  AvatarCity(name: 'Porto-Novo',      country: 'Benin',                      flag: '🇧🇯', svgPath: 'assets/avatars/porto-novo.svg'),
  AvatarCity(name: 'Gaborone',        country: 'Botswana',                   flag: '🇧🇼', svgPath: 'assets/avatars/gaborone.svg'),
  AvatarCity(name: 'Ouagadougou',     country: 'Burkina Faso',               flag: '🇧🇫', svgPath: 'assets/avatars/ouagadougou.svg'),
  AvatarCity(name: 'Gitega',          country: 'Burundi',                    flag: '🇧🇮', svgPath: 'assets/avatars/gitega.svg'),
  AvatarCity(name: 'Yaoundé',         country: 'Cameroon',                   flag: '🇨🇲', svgPath: 'assets/avatars/yaounde.svg'),
  AvatarCity(name: 'Praia',           country: 'Cape Verde',                 flag: '🇨🇻', svgPath: 'assets/avatars/praia.svg'),
  AvatarCity(name: 'Bangui',          country: 'Central African Republic',   flag: '🇨🇫', svgPath: 'assets/avatars/bangui.svg'),
  AvatarCity(name: "N'Djamena",       country: 'Chad',                       flag: '🇹🇩', svgPath: 'assets/avatars/ndjamena.svg'),
  AvatarCity(name: 'Moroni',          country: 'Comoros',                    flag: '🇰🇲', svgPath: 'assets/avatars/moroni.svg'),
  AvatarCity(name: 'Brazzaville',     country: 'Republic of Congo',          flag: '🇨🇬', svgPath: 'assets/avatars/brazzaville.svg'),
  AvatarCity(name: 'Kinshasa',        country: 'DR Congo',                   flag: '🇨🇩', svgPath: 'assets/avatars/kinshasa.svg'),
  AvatarCity(name: 'Djibouti',        country: 'Djibouti',                   flag: '🇩🇯', svgPath: 'assets/avatars/djibouti.svg'),
  AvatarCity(name: 'Cairo',           country: 'Egypt',                      flag: '🇪🇬', svgPath: 'assets/avatars/cairo.svg'),
  AvatarCity(name: 'Malabo',          country: 'Equatorial Guinea',          flag: '🇬🇶', svgPath: 'assets/avatars/malabo.svg'),
  AvatarCity(name: 'Asmara',          country: 'Eritrea',                    flag: '🇪🇷', svgPath: 'assets/avatars/asmara.svg'),
  AvatarCity(name: 'Mbabane',         country: 'Eswatini',                   flag: '🇸🇿', svgPath: 'assets/avatars/mbabane.svg'),
  AvatarCity(name: 'Addis Ababa',     country: 'Ethiopia',                   flag: '🇪🇹', svgPath: 'assets/avatars/addis-ababa.svg'),
  AvatarCity(name: 'Libreville',      country: 'Gabon',                      flag: '🇬🇦', svgPath: 'assets/avatars/libreville.svg'),
  AvatarCity(name: 'Banjul',          country: 'Gambia',                     flag: '🇬🇲', svgPath: 'assets/avatars/banjul.svg'),
  AvatarCity(name: 'Accra',           country: 'Ghana',                      flag: '🇬🇭', svgPath: 'assets/avatars/accra.svg'),
  AvatarCity(name: 'Conakry',         country: 'Guinea',                     flag: '🇬🇳', svgPath: 'assets/avatars/conakry.svg'),
  AvatarCity(name: 'Bissau',          country: 'Guinea-Bissau',              flag: '🇬🇼', svgPath: 'assets/avatars/bissau.svg'),
  AvatarCity(name: 'Yamoussoukro',    country: 'Ivory Coast',                flag: '🇨🇮', svgPath: 'assets/avatars/yamoussoukro.svg'),
  AvatarCity(name: 'Nairobi',         country: 'Kenya',                      flag: '🇰🇪', svgPath: 'assets/avatars/nairobi.svg'),
  AvatarCity(name: 'Maseru',          country: 'Lesotho',                    flag: '🇱🇸', svgPath: 'assets/avatars/maseru.svg'),
  AvatarCity(name: 'Monrovia',        country: 'Liberia',                    flag: '🇱🇷', svgPath: 'assets/avatars/monrovia.svg'),
  AvatarCity(name: 'Tripoli',         country: 'Libya',                      flag: '🇱🇾', svgPath: 'assets/avatars/tripoli.svg'),
  AvatarCity(name: 'Antananarivo',    country: 'Madagascar',                 flag: '🇲🇬', svgPath: 'assets/avatars/antananarivo.svg'),
  AvatarCity(name: 'Lilongwe',        country: 'Malawi',                     flag: '🇲🇼', svgPath: 'assets/avatars/lilongwe.svg'),
  AvatarCity(name: 'Bamako',          country: 'Mali',                       flag: '🇲🇱', svgPath: 'assets/avatars/bamako.svg'),
  AvatarCity(name: 'Nouakchott',      country: 'Mauritania',                 flag: '🇲🇷', svgPath: 'assets/avatars/nouakchott.svg'),
  AvatarCity(name: 'Port Louis',      country: 'Mauritius',                  flag: '🇲🇺', svgPath: 'assets/avatars/port-louis.svg'),
  AvatarCity(name: 'Rabat',           country: 'Morocco',                    flag: '🇲🇦', svgPath: 'assets/avatars/rabat.svg'),
  AvatarCity(name: 'Maputo',          country: 'Mozambique',                 flag: '🇲🇿', svgPath: 'assets/avatars/maputo.svg'),
  AvatarCity(name: 'Windhoek',        country: 'Namibia',                    flag: '🇳🇦', svgPath: 'assets/avatars/windhoek.svg'),
  AvatarCity(name: 'Niamey',          country: 'Niger',                      flag: '🇳🇪', svgPath: 'assets/avatars/niamey.svg'),
  AvatarCity(name: 'Abuja',           country: 'Nigeria',                    flag: '🇳🇬', svgPath: 'assets/avatars/abuja.svg'),
  AvatarCity(name: 'Kigali',          country: 'Rwanda',                     flag: '🇷🇼', svgPath: 'assets/avatars/kigali.svg'),
  AvatarCity(name: 'São Tomé',        country: 'São Tomé and Príncipe',      flag: '🇸🇹', svgPath: 'assets/avatars/sao-tome.svg'),
  AvatarCity(name: 'Dakar',           country: 'Senegal',                    flag: '🇸🇳', svgPath: 'assets/avatars/dakar.svg'),
  AvatarCity(name: 'Victoria',        country: 'Seychelles',                 flag: '🇸🇨', svgPath: 'assets/avatars/victoria.svg'),
  AvatarCity(name: 'Freetown',        country: 'Sierra Leone',               flag: '🇸🇱', svgPath: 'assets/avatars/freetown.svg'),
  AvatarCity(name: 'Mogadishu',       country: 'Somalia',                    flag: '🇸🇴', svgPath: 'assets/avatars/mogadishu.svg'),
  AvatarCity(name: 'Pretoria',        country: 'South Africa',               flag: '🇿🇦', svgPath: 'assets/avatars/pretoria.svg'),
  AvatarCity(name: 'Juba',            country: 'South Sudan',                flag: '🇸🇸', svgPath: 'assets/avatars/juba.svg'),
  AvatarCity(name: 'Khartoum',        country: 'Sudan',                      flag: '🇸🇩', svgPath: 'assets/avatars/khartoum.svg'),
  AvatarCity(name: 'Dodoma',          country: 'Tanzania',                   flag: '🇹🇿', svgPath: 'assets/avatars/dodoma.svg'),
  AvatarCity(name: 'Lomé',            country: 'Togo',                       flag: '🇹🇬', svgPath: 'assets/avatars/lome.svg'),
  AvatarCity(name: 'Tunis',           country: 'Tunisia',                    flag: '🇹🇳', svgPath: 'assets/avatars/tunis.svg'),
  AvatarCity(name: 'Kampala',         country: 'Uganda',                     flag: '🇺🇬', svgPath: 'assets/avatars/kampala.svg'),
  AvatarCity(name: 'Lusaka',          country: 'Zambia',                     flag: '🇿🇲', svgPath: 'assets/avatars/lusaka.svg'),
  AvatarCity(name: 'Harare',          country: 'Zimbabwe',                   flag: '🇿🇼', svgPath: 'assets/avatars/harare.svg'),

  // ── Asia ───────────────────────────────────────────────────────────────────
  AvatarCity(name: 'Kabul',                   country: 'Afghanistan',  flag: '🇦🇫', svgPath: 'assets/avatars/kabul.svg'),
  AvatarCity(name: 'Yerevan',                 country: 'Armenia',      flag: '🇦🇲', svgPath: 'assets/avatars/yerevan.svg'),
  AvatarCity(name: 'Baku',                    country: 'Azerbaijan',   flag: '🇦🇿', svgPath: 'assets/avatars/baku.svg'),
  AvatarCity(name: 'Manama',                  country: 'Bahrain',      flag: '🇧🇭', svgPath: 'assets/avatars/manama.svg'),
  AvatarCity(name: 'Dhaka',                   country: 'Bangladesh',   flag: '🇧🇩', svgPath: 'assets/avatars/dhaka.svg'),
  AvatarCity(name: 'Thimphu',                 country: 'Bhutan',       flag: '🇧🇹', svgPath: 'assets/avatars/thimphu.svg'),
  AvatarCity(name: 'Bandar Seri Begawan',     country: 'Brunei',       flag: '🇧🇳', svgPath: 'assets/avatars/bandar-seri-begawan.svg'),
  AvatarCity(name: 'Phnom Penh',              country: 'Cambodia',     flag: '🇰🇭', svgPath: 'assets/avatars/phnom-penh.svg'),
  AvatarCity(name: 'Beijing',                 country: 'China',        flag: '🇨🇳', svgPath: 'assets/avatars/beijing.svg'),
  AvatarCity(name: 'Nicosia',                 country: 'Cyprus',       flag: '🇨🇾', svgPath: 'assets/avatars/nicosia.svg'),
  AvatarCity(name: 'Tbilisi',                 country: 'Georgia',      flag: '🇬🇪', svgPath: 'assets/avatars/tbilisi.svg'),
  AvatarCity(name: 'New Delhi',               country: 'India',        flag: '🇮🇳', svgPath: 'assets/avatars/new-delhi.svg'),
  AvatarCity(name: 'Jakarta',                 country: 'Indonesia',    flag: '🇮🇩', svgPath: 'assets/avatars/jakarta.svg'),
  AvatarCity(name: 'Tehran',                  country: 'Iran',         flag: '🇮🇷', svgPath: 'assets/avatars/tehran.svg'),
  AvatarCity(name: 'Baghdad',                 country: 'Iraq',         flag: '🇮🇶', svgPath: 'assets/avatars/baghdad.svg'),
  AvatarCity(name: 'Jerusalem',               country: 'Israel',       flag: '🇮🇱', svgPath: 'assets/avatars/jerusalem.svg'),
  AvatarCity(name: 'Amman',                   country: 'Jordan',       flag: '🇯🇴', svgPath: 'assets/avatars/amman.svg'),
  AvatarCity(name: 'Astana',                  country: 'Kazakhstan',   flag: '🇰🇿', svgPath: 'assets/avatars/astana.svg'),
  AvatarCity(name: 'Kuwait City',             country: 'Kuwait',       flag: '🇰🇼', svgPath: 'assets/avatars/kuwait-city.svg'),
  AvatarCity(name: 'Bishkek',                 country: 'Kyrgyzstan',   flag: '🇰🇬', svgPath: 'assets/avatars/bishkek.svg'),
  AvatarCity(name: 'Vientiane',               country: 'Laos',         flag: '🇱🇦', svgPath: 'assets/avatars/vientiane.svg'),
  AvatarCity(name: 'Beirut',                  country: 'Lebanon',      flag: '🇱🇧', svgPath: 'assets/avatars/beirut.svg'),
  AvatarCity(name: 'Kuala Lumpur',            country: 'Malaysia',     flag: '🇲🇾', svgPath: 'assets/avatars/kuala-lumpur.svg'),
  AvatarCity(name: 'Malé',                    country: 'Maldives',     flag: '🇲🇻', svgPath: 'assets/avatars/male.svg'),
  AvatarCity(name: 'Ulaanbaatar',             country: 'Mongolia',     flag: '🇲🇳', svgPath: 'assets/avatars/ulaanbaatar.svg'),
  AvatarCity(name: 'Naypyidaw',               country: 'Myanmar',      flag: '🇲🇲', svgPath: 'assets/avatars/naypyidaw.svg'),
  AvatarCity(name: 'Kathmandu',               country: 'Nepal',        flag: '🇳🇵', svgPath: 'assets/avatars/kathmandu.svg'),
  AvatarCity(name: 'Pyongyang',               country: 'North Korea',  flag: '🇰🇵', svgPath: 'assets/avatars/pyongyang.svg'),
  AvatarCity(name: 'Muscat',                  country: 'Oman',         flag: '🇴🇲', svgPath: 'assets/avatars/muscat.svg'),
  AvatarCity(name: 'Islamabad',               country: 'Pakistan',     flag: '🇵🇰', svgPath: 'assets/avatars/islamabad.svg'),
  AvatarCity(name: 'Manila',                  country: 'Philippines',  flag: '🇵🇭', svgPath: 'assets/avatars/manila.svg'),
  AvatarCity(name: 'Doha',                    country: 'Qatar',        flag: '🇶🇦', svgPath: 'assets/avatars/doha.svg'),
  AvatarCity(name: 'Riyadh',                  country: 'Saudi Arabia', flag: '🇸🇦', svgPath: 'assets/avatars/riyadh.svg'),
  AvatarCity(name: 'Singapore',               country: 'Singapore',    flag: '🇸🇬', svgPath: 'assets/avatars/singapore.svg'),
  AvatarCity(name: 'Seoul',                   country: 'South Korea',  flag: '🇰🇷', svgPath: 'assets/avatars/seoul.svg'),
  AvatarCity(name: 'Sri Jayawardenepura',     country: 'Sri Lanka',    flag: '🇱🇰', svgPath: 'assets/avatars/sri-jayawardenepura.svg'),
  AvatarCity(name: 'Damascus',                country: 'Syria',        flag: '🇸🇾', svgPath: 'assets/avatars/damascus.svg'),
  AvatarCity(name: 'Taipei',                  country: 'Taiwan',       flag: '🇹🇼', svgPath: 'assets/avatars/taipei.svg'),
  AvatarCity(name: 'Dushanbe',                country: 'Tajikistan',   flag: '🇹🇯', svgPath: 'assets/avatars/dushanbe.svg'),
  AvatarCity(name: 'Bangkok',                 country: 'Thailand',     flag: '🇹🇭', svgPath: 'assets/avatars/bangkok.svg'),
  AvatarCity(name: 'Dili',                    country: 'Timor-Leste',  flag: '🇹🇱', svgPath: 'assets/avatars/dili.svg'),
  AvatarCity(name: 'Ankara',                  country: 'Turkey',       flag: '🇹🇷', svgPath: 'assets/avatars/ankara.svg'),
  AvatarCity(name: 'Ashgabat',                country: 'Turkmenistan', flag: '🇹🇲', svgPath: 'assets/avatars/ashgabat.svg'),
  AvatarCity(name: 'Abu Dhabi',               country: 'UAE',          flag: '🇦🇪', svgPath: 'assets/avatars/abu-dhabi.svg'),
  AvatarCity(name: 'Tashkent',                country: 'Uzbekistan',   flag: '🇺🇿', svgPath: 'assets/avatars/tashkent.svg'),
  AvatarCity(name: 'Hanoi',                   country: 'Vietnam',      flag: '🇻🇳', svgPath: 'assets/avatars/hanoi.svg'),
  AvatarCity(name: 'Sanaa',                   country: 'Yemen',        flag: '🇾🇪', svgPath: 'assets/avatars/sanaa.svg'),

  // ── Europe ─────────────────────────────────────────────────────────────────
  AvatarCity(name: 'Tirana',          country: 'Albania',          flag: '🇦🇱', svgPath: 'assets/avatars/tirana.svg'),
  AvatarCity(name: 'Andorra la Vella',country: 'Andorra',          flag: '🇦🇩', svgPath: 'assets/avatars/andorra-la-vella.svg'),
  AvatarCity(name: 'Vienna',          country: 'Austria',          flag: '🇦🇹', svgPath: 'assets/avatars/vienna.svg'),
  AvatarCity(name: 'Minsk',           country: 'Belarus',          flag: '🇧🇾', svgPath: 'assets/avatars/minsk.svg'),
  AvatarCity(name: 'Brussels',        country: 'Belgium',          flag: '🇧🇪', svgPath: 'assets/avatars/brussels.svg'),
  AvatarCity(name: 'Sarajevo',        country: 'Bosnia',           flag: '🇧🇦', svgPath: 'assets/avatars/sarajevo.svg'),
  AvatarCity(name: 'Sofia',           country: 'Bulgaria',         flag: '🇧🇬', svgPath: 'assets/avatars/sofia.svg'),
  AvatarCity(name: 'Zagreb',          country: 'Croatia',          flag: '🇭🇷', svgPath: 'assets/avatars/zagreb.svg'),
  AvatarCity(name: 'Prague',          country: 'Czech Republic',   flag: '🇨🇿', svgPath: 'assets/avatars/prague.svg'),
  AvatarCity(name: 'Copenhagen',      country: 'Denmark',          flag: '🇩🇰', svgPath: 'assets/avatars/copenhagen.svg'),
  AvatarCity(name: 'Tallinn',         country: 'Estonia',          flag: '🇪🇪', svgPath: 'assets/avatars/tallinn.svg'),
  AvatarCity(name: 'Helsinki',        country: 'Finland',          flag: '🇫🇮', svgPath: 'assets/avatars/helsinki.svg'),
  AvatarCity(name: 'Berlin',          country: 'Germany',          flag: '🇩🇪', svgPath: 'assets/avatars/berlin.svg'),
  AvatarCity(name: 'Athens',          country: 'Greece',           flag: '🇬🇷', svgPath: 'assets/avatars/athens.svg'),
  AvatarCity(name: 'Budapest',        country: 'Hungary',          flag: '🇭🇺', svgPath: 'assets/avatars/budapest.svg'),
  AvatarCity(name: 'Reykjavik',       country: 'Iceland',          flag: '🇮🇸', svgPath: 'assets/avatars/reykjavik.svg'),
  AvatarCity(name: 'Dublin',          country: 'Ireland',          flag: '🇮🇪', svgPath: 'assets/avatars/dublin.svg'),
  AvatarCity(name: 'Pristina',        country: 'Kosovo',           flag: '🇽🇰', svgPath: 'assets/avatars/pristina.svg'),
  AvatarCity(name: 'Riga',            country: 'Latvia',           flag: '🇱🇻', svgPath: 'assets/avatars/riga.svg'),
  AvatarCity(name: 'Vaduz',           country: 'Liechtenstein',    flag: '🇱🇮', svgPath: 'assets/avatars/vaduz.svg'),
  AvatarCity(name: 'Vilnius',         country: 'Lithuania',        flag: '🇱🇹', svgPath: 'assets/avatars/vilnius.svg'),
  AvatarCity(name: 'Luxembourg City', country: 'Luxembourg',       flag: '🇱🇺', svgPath: 'assets/avatars/luxembourg-city.svg'),
  AvatarCity(name: 'Valletta',        country: 'Malta',            flag: '🇲🇹', svgPath: 'assets/avatars/valletta.svg'),
  AvatarCity(name: 'Chișinău',        country: 'Moldova',          flag: '🇲🇩', svgPath: 'assets/avatars/chisinau.svg'),
  AvatarCity(name: 'Monaco',          country: 'Monaco',           flag: '🇲🇨', svgPath: 'assets/avatars/monaco.svg'),
  AvatarCity(name: 'Podgorica',       country: 'Montenegro',       flag: '🇲🇪', svgPath: 'assets/avatars/podgorica.svg'),
  AvatarCity(name: 'Amsterdam',       country: 'Netherlands',      flag: '🇳🇱', svgPath: 'assets/avatars/amsterdam.svg'),
  AvatarCity(name: 'Skopje',          country: 'North Macedonia',  flag: '🇲🇰', svgPath: 'assets/avatars/skopje.svg'),
  AvatarCity(name: 'Oslo',            country: 'Norway',           flag: '🇳🇴', svgPath: 'assets/avatars/oslo.svg'),
  AvatarCity(name: 'Lisbon',          country: 'Portugal',         flag: '🇵🇹', svgPath: 'assets/avatars/lisbon.svg'),
  AvatarCity(name: 'Bucharest',       country: 'Romania',          flag: '🇷🇴', svgPath: 'assets/avatars/bucharest.svg'),
  AvatarCity(name: 'Moscow',          country: 'Russia',           flag: '🇷🇺', svgPath: 'assets/avatars/moscow.svg'),
  AvatarCity(name: 'San Marino',      country: 'San Marino',       flag: '🇸🇲', svgPath: 'assets/avatars/san-marino.svg'),
  AvatarCity(name: 'Belgrade',        country: 'Serbia',           flag: '🇷🇸', svgPath: 'assets/avatars/belgrade.svg'),
  AvatarCity(name: 'Bratislava',      country: 'Slovakia',         flag: '🇸🇰', svgPath: 'assets/avatars/bratislava.svg'),
  AvatarCity(name: 'Ljubljana',       country: 'Slovenia',         flag: '🇸🇮', svgPath: 'assets/avatars/ljubljana.svg'),
  AvatarCity(name: 'Madrid',          country: 'Spain',            flag: '🇪🇸', svgPath: 'assets/avatars/madrid.svg'),
  AvatarCity(name: 'Stockholm',       country: 'Sweden',           flag: '🇸🇪', svgPath: 'assets/avatars/stockholm.svg'),
  AvatarCity(name: 'Bern',            country: 'Switzerland',      flag: '🇨🇭', svgPath: 'assets/avatars/bern.svg'),
  AvatarCity(name: 'Kyiv',            country: 'Ukraine',          flag: '🇺🇦', svgPath: 'assets/avatars/kyiv.svg'),
  AvatarCity(name: 'Vatican City',    country: 'Vatican',          flag: '🇻🇦', svgPath: 'assets/avatars/vatican-city.svg'),

  // ── Americas ───────────────────────────────────────────────────────────────
  AvatarCity(name: "St. John's",      country: 'Antigua and Barbuda',    flag: '🇦🇬', svgPath: 'assets/avatars/st-johns.svg'),
  AvatarCity(name: 'Buenos Aires',    country: 'Argentina',              flag: '🇦🇷', svgPath: 'assets/avatars/buenos-aires.svg'),
  AvatarCity(name: 'Nassau',          country: 'Bahamas',                flag: '🇧🇸', svgPath: 'assets/avatars/nassau.svg'),
  AvatarCity(name: 'Bridgetown',      country: 'Barbados',               flag: '🇧🇧', svgPath: 'assets/avatars/bridgetown.svg'),
  AvatarCity(name: 'Belmopan',        country: 'Belize',                 flag: '🇧🇿', svgPath: 'assets/avatars/belmopan.svg'),
  AvatarCity(name: 'Sucre',           country: 'Bolivia',                flag: '🇧🇴', svgPath: 'assets/avatars/sucre.svg'),
  AvatarCity(name: 'Brasília',        country: 'Brazil',                 flag: '🇧🇷', svgPath: 'assets/avatars/brasilia.svg'),
  AvatarCity(name: 'Ottawa',          country: 'Canada',                 flag: '🇨🇦', svgPath: 'assets/avatars/ottawa.svg'),
  AvatarCity(name: 'Santiago',        country: 'Chile',                  flag: '🇨🇱', svgPath: 'assets/avatars/santiago.svg'),
  AvatarCity(name: 'Bogotá',          country: 'Colombia',               flag: '🇨🇴', svgPath: 'assets/avatars/bogota.svg'),
  AvatarCity(name: 'San José',        country: 'Costa Rica',             flag: '🇨🇷', svgPath: 'assets/avatars/san-jose.svg'),
  AvatarCity(name: 'Havana',          country: 'Cuba',                   flag: '🇨🇺', svgPath: 'assets/avatars/havana.svg'),
  AvatarCity(name: 'Roseau',          country: 'Dominica',               flag: '🇩🇲', svgPath: 'assets/avatars/roseau.svg'),
  AvatarCity(name: 'Santo Domingo',   country: 'Dominican Republic',     flag: '🇩🇴', svgPath: 'assets/avatars/santo-domingo.svg'),
  AvatarCity(name: 'Quito',           country: 'Ecuador',                flag: '🇪🇨', svgPath: 'assets/avatars/quito.svg'),
  AvatarCity(name: 'San Salvador',    country: 'El Salvador',            flag: '🇸🇻', svgPath: 'assets/avatars/san-salvador.svg'),
  AvatarCity(name: "St. George's",    country: 'Grenada',                flag: '🇬🇩', svgPath: 'assets/avatars/st-georges.svg'),
  AvatarCity(name: 'Guatemala City',  country: 'Guatemala',              flag: '🇬🇹', svgPath: 'assets/avatars/guatemala-city.svg'),
  AvatarCity(name: 'Georgetown',      country: 'Guyana',                 flag: '🇬🇾', svgPath: 'assets/avatars/georgetown.svg'),
  AvatarCity(name: 'Port-au-Prince',  country: 'Haiti',                  flag: '🇭🇹', svgPath: 'assets/avatars/port-au-prince.svg'),
  AvatarCity(name: 'Tegucigalpa',     country: 'Honduras',               flag: '🇭🇳', svgPath: 'assets/avatars/tegucigalpa.svg'),
  AvatarCity(name: 'Kingston',        country: 'Jamaica',                flag: '🇯🇲', svgPath: 'assets/avatars/kingston.svg'),
  AvatarCity(name: 'Mexico City',     country: 'Mexico',                 flag: '🇲🇽', svgPath: 'assets/avatars/mexico-city.svg'),
  AvatarCity(name: 'Managua',         country: 'Nicaragua',              flag: '🇳🇮', svgPath: 'assets/avatars/managua.svg'),
  AvatarCity(name: 'Panama City',     country: 'Panama',                 flag: '🇵🇦', svgPath: 'assets/avatars/panama-city.svg'),
  AvatarCity(name: 'Asunción',        country: 'Paraguay',               flag: '🇵🇾', svgPath: 'assets/avatars/asuncion.svg'),
  AvatarCity(name: 'Lima',            country: 'Peru',                   flag: '🇵🇪', svgPath: 'assets/avatars/lima.svg'),
  AvatarCity(name: 'Basseterre',      country: 'Saint Kitts and Nevis',  flag: '🇰🇳', svgPath: 'assets/avatars/basseterre.svg'),
  AvatarCity(name: 'Castries',        country: 'Saint Lucia',            flag: '🇱🇨', svgPath: 'assets/avatars/castries.svg'),
  AvatarCity(name: 'Kingstown',       country: 'Saint Vincent',          flag: '🇻🇨', svgPath: 'assets/avatars/kingstown.svg'),
  AvatarCity(name: 'Paramaribo',      country: 'Suriname',               flag: '🇸🇷', svgPath: 'assets/avatars/paramaribo.svg'),
  AvatarCity(name: 'Port of Spain',   country: 'Trinidad and Tobago',    flag: '🇹🇹', svgPath: 'assets/avatars/port-of-spain.svg'),
  AvatarCity(name: 'Montevideo',      country: 'Uruguay',                flag: '🇺🇾', svgPath: 'assets/avatars/montevideo.svg'),
  AvatarCity(name: 'Washington D.C.', country: 'USA',                    flag: '🇺🇸', svgPath: 'assets/avatars/washington-dc.svg'),
  AvatarCity(name: 'Caracas',         country: 'Venezuela',              flag: '🇻🇪', svgPath: 'assets/avatars/caracas.svg'),

  // ── Oceania ────────────────────────────────────────────────────────────────
  AvatarCity(name: 'Canberra',      country: 'Australia',        flag: '🇦🇺', svgPath: 'assets/avatars/canberra.svg'),
  AvatarCity(name: 'Suva',          country: 'Fiji',             flag: '🇫🇯', svgPath: 'assets/avatars/suva.svg'),
  AvatarCity(name: 'South Tarawa',  country: 'Kiribati',         flag: '🇰🇮', svgPath: 'assets/avatars/south-tarawa.svg'),
  AvatarCity(name: 'Majuro',        country: 'Marshall Islands', flag: '🇲🇭', svgPath: 'assets/avatars/majuro.svg'),
  AvatarCity(name: 'Palikir',       country: 'Micronesia',       flag: '🇫🇲', svgPath: 'assets/avatars/palikir.svg'),
  AvatarCity(name: 'Yaren',         country: 'Nauru',            flag: '🇳🇷', svgPath: 'assets/avatars/yaren.svg'),
  AvatarCity(name: 'Wellington',    country: 'New Zealand',      flag: '🇳🇿', svgPath: 'assets/avatars/wellington.svg'),
  AvatarCity(name: 'Ngerulmud',     country: 'Palau',            flag: '🇵🇼', svgPath: 'assets/avatars/ngerulmud.svg'),
  AvatarCity(name: 'Port Moresby',  country: 'Papua New Guinea', flag: '🇵🇬', svgPath: 'assets/avatars/port-moresby.svg'),
  AvatarCity(name: 'Apia',          country: 'Samoa',            flag: '🇼🇸', svgPath: 'assets/avatars/apia.svg'),
  AvatarCity(name: 'Honiara',       country: 'Solomon Islands',  flag: '🇸🇧', svgPath: 'assets/avatars/honiara.svg'),
  AvatarCity(name: "Nuku'alofa",    country: 'Tonga',            flag: '🇹🇴', svgPath: 'assets/avatars/nuku-alofa.svg'),
  AvatarCity(name: 'Funafuti',      country: 'Tuvalu',           flag: '🇹🇻', svgPath: 'assets/avatars/funafuti.svg'),
  AvatarCity(name: 'Port Vila',     country: 'Vanuatu',          flag: '🇻🇺', svgPath: 'assets/avatars/port-vila.svg'),
];
